---
- name: Remove web server
  hosts: all

  tasks:
  - name: Remove {{ web_server }} package
    package: 
      name: "{{ web_server }}"
      state: absent
 
  - name: Remove index.html
    file:
      path: /var/www/html/index.html
      state: absent

  - name: Close http firewalld
    firewalld:
      service: http
      permanent: true
      state: disabled
      immediate: yes

  - name: Close https firewald
    firewalld: 
      service: https
      permanent: true
      state: disabled
      immediate: yes
