---
- name: Change grub file
  hosts: all

  tasks:
  - name: Add parameters
    lineinfile:
      path: /etc/default/grub
      regexp: 'GRUB_CMDLINE_LINUX.*'
      line: 'GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/cl-swap rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet net.ifnames=0 biosdevname=0"'      

  - name: Write changes
    command: grub2-mkconfig
